//
// Created by yekai on 2021/7/10.
//

#ifndef ROTARYINVERTEDPENDULUM_DEBUG_CONF_H
#define ROTARYINVERTEDPENDULUM_DEBUG_CONF_H

//#define ADC_DEBUG
#define OUT_DEBUG
//#define MOTOR_DEBUG

#endif //ROTARYINVERTEDPENDULUM_DEBUG_CONF_H
